### ISSUE TITLE
Call to a member function canEdit() on null when deleting a forum post.

### ISSUE THREAD

**Issue by LaravelNick** [rainlab/forum-plugin#100]
When editing a post, I click delete, acknowledge the 'Are you sure?' dialog after which I am immediately presented with another 'Are you sure?' dialog, followed by a popup within the following error message:-

"Call to a member function canEdit() on null" on line 386 <path-to-my-project>/plugins/rainlab/forum/components/Topic.php

The post gets deleted, but something is obviously causing it to attempt to delete it a second time, and of course a null reference exception is thrown the second time, as the post has already been deleted.

No Javascript errors are thrown.

I'm using the latest version of October CMS and the latest version of rainlab / forum.

I've tried systematically removing references to other Javascript plugins that I'm using, but the issue persists.

Any help would be gratefully appreciated please.

**Comment by daftspunk** [comment]
Sounds like a logic error. Will take a look. Thanks

**Comment by daftspunk** [comment]
I was unable to replicate this using standard workflows. Either way, there is now some code included to pick up on these occurrences (cbdff586db15804b066df022bd57e28afcfc5964).

**Comment by LaravelNick** [comment]
Thank you very much for that Samuel.

**Comment by LaravelNick** [comment]
I've just tracked down the cause of the form posting back twice.

I had {% framework extras %} in my layout.

I removed that and now the form no longer posts twice.
