### ISSUE TITLE
RainLab.User names with 2+ words cause RainLab.Forum name to default to email handle

### ISSUE THREAD

**Issue by Cleanse** [rainlab/forum-plugin#101]
Can we get support for `First Last` name imports? Creating a slug with hyphens for spaces works.

**Comment by bhargavy** [comment]
+1

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
