### ISSUE TITLE
error when posting replies

### ISSUE THREAD

**Issue by lponganLR** [rainlab/forum-plugin#103]
I get an exception "A non-numeric value encountered" whenever trying to post a reply to an existing topic. I believe this is because the return url includes page=last instead of a numeric value like page=1.

**Comment by H6** [comment]
I have the same issue. `$currentPage` is used to build the scope query"
```
            $posts = PostModel::with('member.user.avatar')->listFrontEnd([
                'page'    => $currentPage,
                'perPage' => $this->property('postsPerPage'),
                'sort'    => 'created_at',
                'topic'   => $topic->id,
                'search'  => $searchString,
            ]);
```

**Comment by H6** [comment]
I have created some fix for this in https://github.com/rainlab/forum-plugin/pull/104 ... maybe it helps.. It works on my site now...

**Comment by daftspunk** [comment]
I wasn't able to replicate this using the vanilla theme: https://github.com/rainlab/vanilla-theme

This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by lponganLR** [comment]
Bug summary: I get an exception "A non-numeric value encountered" whenever trying to post a reply to an existing topic. I believe this is because the return url includes page=last instead of a numeric value like page=1.

Request location: Forum topic reply

Reproduce steps: click on an existing forum topic. write a reply. click post a reply button.

Expected behavior: Your post is added to the topic and you redirected back to the topic thread to see your post.

Actual behavior: The post gets added, but the redirect url throws an exception.
![screen shot 2017-01-18 at 9 06 45 am](https://cloud.githubusercontent.com/assets/23361184/22071811/9c1da712-dd5d-11e6-97c6-4ec6e19e4a4f.png)

**Comment by Teranode** [comment]
@daftspunk this error is specific to PHP 7.1 version below that wont get this error

**Comment by Teranode** [comment]
I see the issue,
Laravel doesnt allow the "last" string to be used in page so
`{{ channel.first_topic.url }}page=last#post-{{ channel.first_topic.last_post_id }}`
wont work
you have to use a number for the last page.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
