### ISSUE TITLE
Feature Req: User Groups / Roles?

### ISSUE THREAD

**Issue by AugmentBLU** [rainlab/forum-plugin#107]
Hello,

it would be great if we could get some form of user group/role permissions native to the CMS for the forum. Many sites that use a forum require a few channels that are for admins, staff or whatever.

Thanks!

**Comment by Teranode** [comment]
I dont think that would be wise for the forum plugin rather yo should use extensions from your own roles/perm plugin for the forum plugins

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
