### ISSUE TITLE
[question] how to moderate blog posts

### ISSUE THREAD

**Issue by webeks** [rainlab/forum-plugin#109]
Preparing forum for our site. However I can't seem to find any moderation button on posts neither can I find any mention how to moderate posts in docs? 

Any insights?
Thanks!

**Comment by thechrise** [comment]
Along with that, is there any way to for users to report inappropriate posts to admin/moderators?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
