### ISSUE TITLE
Bug php 7.1

### ISSUE THREAD

**Issue by RinWorld** [rainlab/forum-plugin#112]
Sorry, clone issues

------------
The bug occurs on php 7.1 when you send a message, the forum does redirect to the last page, pointing it to the address bar as last, but with some introductions to php 7.1 this is a mistake. How do you figure out the output of the last page?

Screenshot
http://prntscr.com/h6fy0n

`return Redirect::to($redirectUrl.'?page=**last**#post-'.$post->id);`

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/library/commit/384024082f8425e45c3b308af4a3deb2c5f17aaf

This should be fixed in Build 423+
