### ISSUE TITLE
Bug: Component "forumChannels"

### ISSUE THREAD

**Issue by ahren88** [rainlab/forum-plugin#113]
Hi all,

i have find bug on this page component "plugin/rainlab/components/channels/default.htm".

Line 15: {% if channel.relations.children %}

Replaced with:
Line 15: {% if channel.children %}

Now see list channels.

Sorry all for my bad english.
Thank's

**Comment by LukeTowers** [comment]
What build of October are you using and what version of the plugin?

**Comment by ahren88** [comment]
Hi Luke,
I use the 428 build october and last version plugin.
I have update all

**Comment by LukeTowers** [comment]
What happens with the old "broken" code vs the new fixed code?

**Comment by ahren88** [comment]
Before i could not see the channels list with message: "_There are no channels to show._".
Now i see the complete channels list excluded the private channels or hidden channels.

there is no exist reference channel.**relations**.children, but exist **_channel.children_**

**Comment by LukeTowers** [comment]
@ahren88 do you know of anyone else having this issue?

**Comment by JoakimBo** [comment]
Both of these worked when I quickly tested it. Both `channel.children` and `channel.relations.children` points to a lists method which got the channel children. Either it has been fixed between when this issue was originally posted or this might be a configuration issue?.
