### ISSUE TITLE
Forum Channels not showing on main forum page.

### ISSUE THREAD

**Issue by BKoehler** [rainlab/forum-plugin#114]
I recently discovered October CMS and in learning the system, I have run into a problem. When implementing the forum, none of the channels are showing. I created them, but the page says there are no channels to show. I am very perplexed by this. Any assistance would be appreciated.

**Comment by LukeTowers** [comment]
@BKoehler is this related to #113?

**Comment by BKoehler** [comment]
I actually had the issue resolve itself somehow. I am currently using build 430, but have run into a second issue. After logging in, When I click the button to create my first topic, it states no topics found instead of the form to create a topic.

**Comment by BKoehler** [comment]
My apologies,
I accidentally closed the comment
