### ISSUE TITLE
Run custom code when creating new channel

### ISSUE THREAD

**Issue by WouterBagger** [rainlab/forum-plugin#115]
Hi,

we'd like to use the forum plugin in our solution. One thing we're missing is the ability to execute some custom code of ours when a new channel is created. Do you have any advice on doing this?

Thanks in advance!
Wouter

**Comment by LukeTowers** [comment]
```php
\RainLab\Forum\Models\Channel::extend(function ($model) {
    $model->bindEvent('model.onCreate', function () use ($model) {
        // custom code here
    });
});
```
