### ISSUE TITLE
Forum member posts avatars not showing when not logged in

### ISSUE THREAD

**Issue by drisschelouati** [rainlab/forum-plugin#117]
Hello, i have another question about the forum plugin. On the website iam currently developing, i have static pages and blog posts with embedded forum topics, used as comment sections.

The forum is not available for guest users, it is only for logged in users (Iam using the session component from the user plugin to control this). So the question doesn't concern the main forum, but only the embedded topics.

**1. Steps to reproduce**

I embedded a topic in a static (or a blog post page, it doesn't matter). I modified the component templates to fit my needs (by following the good practice and creating my own partials). Here is how i handle post avatars in `post.htm` : 

```twig
    {% if post.member.user.avatar.count %}
    
        <img class='is-50' src="{{ member.user.avatarThumb(50) }}" alt="{{ member.username }}" />
        
    {% else %}

        <img class='is-50' src="{{'assets/images/avatars/avatar.png'|theme}}" alt="{{ member.username }}">

    {% endif %}
```
**2. Expected behaviour**

Check if the user associated with the post has an avatar. If he has one, display it, if not display the default avatar placeholder (avatar.png).

**3. What actually happens**

If the user is logged in, embedded topic avatars are displayed as expected. But if the user is logged out, no image is shown altough the space it is supposed to occupy is left blank but keeps the element original size. Inspecting the img elements with the browser showed `src(unknown)`.

**4. My temporary fix**

I added a javascript error handler to minimize the impact of this problem. In my embedded topic partials, i use the following handler for post avatar images: 

`onError="this.onerror=null;this.src='/path/to/avatar.png';"`

This at least lets me display the default avatar rather than a blank space for guests. However, i would like to know if it is still possible to diplay the avatars for non logged in users.

Did i miss something ?

**Comment by LukeTowers** [comment]
Please use three backticks to surround code blocks, not just one.

**Comment by LukeTowers** [comment]
I'm not sure I understand what's going on exactly, which of the two code branches in your paste is getting run in the situation where the src is being set to unknown?

**Comment by drisschelouati** [comment]
Iam sure it's the first branch : 

```
{% if post.member.user.avatar.count %}
    
        <img class='is-50' src="{{ member.user.avatarThumb(50) }}" alt="{{ member.username }}" />

```

But somehow, src data is not returned correctly. Let me show you some screenshots so you see what is going on : 

**Logged in user (works as expected)**

![loggedin](https://user-images.githubusercontent.com/12543068/34644795-44136158-f335-11e7-9671-2ad506e61962.PNG)

**Logged out user (Breaks)**

![loggedout](https://user-images.githubusercontent.com/12543068/34644804-667bde1e-f335-11e7-8e32-62a3eb2ae188.PNG)

**Logged out user (With my javascript error handling, all avatars forced to default)**

![loggedoutfix](https://user-images.githubusercontent.com/12543068/34644807-7d5867b0-f335-11e7-86ed-79b465e73119.PNG)


I hope this helps to understand the issue better.

**Comment by LukeTowers** [comment]
I think I see the issue:
You're checking for `post.member.user.avatar.count` but trying to use `member.user.avatarThumb`. Try using `post.member.user.avatarThumb`; I'm guessing that the `member` variable doesn't exist when the user isn't logged in.

**Comment by drisschelouati** [comment]
You were right, i was simply calling the wrong variable. I still need to dig more to improve on available variables. Thank you for your support.

**Comment by LukeTowers** [comment]
No problem, happy to help!
