### ISSUE TITLE
Error in "reply to this discussion"

### ISSUE THREAD

**Issue by HekmatFavid** [rainlab/forum-plugin#123]
I post a new topic and it save properly but when reply to this discussion or quote attached error message appear and after back to prevoius page all reply or quote saved properly.

https://photos.app.goo.gl/ulxNa3MUOyTZfbuj1

**Comment by HekmatFavid** [comment]
It works properly in php 5.6, but php 7.1 has the non-numeric value encountered problem.

**Comment by LukeTowers** [comment]
@HekmatFavid update your base OctoberCMS installation (will require PHP 7)
