### ISSUE TITLE
The word "discussion" is misspelled in the seed data

### ISSUE THREAD

**Issue by immersiontravis** [rainlab/forum-plugin#125]
This is a super minor issue, but: in updates/seed_all_tables.php, the word "discussion" is repeatedly misspelled (it appears in that file as "disccusion").

**Comment by LukeTowers** [comment]
@immersiontravis feel free to submit a PR to fix it, just edit the file, no need for a new migration

**Comment by immersiontravis** [comment]
Done:

https://github.com/rainlab/forum-plugin/pull/126
