### ISSUE TITLE
Fire events

### ISSUE THREAD

**Issue by briddle** [rainlab/forum-plugin#129]
Is it possible to add firing events onPost etc.?

**Comment by LukeTowers** [comment]
Propose the events that you wanted added, what parameters would be expected, and where exactly you want it and we'll consider it.

**Comment by briddle** [comment]
Hi Luke,

I noticed that the Forum plugin actually has 2 events: rainlab.forum.topic.post and rainlab.forum.topic.create. I missed those as it was late and my brain shuts down if a baby cries in the background :( 

These 2 events are fine for me. Closing
