### ISSUE TITLE
EmbedChannel component bug

### ISSUE THREAD

**Issue by VadimIzmalkov** [rainlab/forum-plugin#130]
Got error after put EmbedChannel component on a page and open component properties:

`The component 'RainLab\Forum\Components\EmbedChannel' does not contain a method 'getChannelSlugOptions'`

![default](https://user-images.githubusercontent.com/6684336/46792135-4e051f80-cd4b-11e8-9ff7-6dca717f3803.png)

Method getChannelSlugOptions() set as protected

**Comment by LukeTowers** [comment]
@VadimIzmalkov I wonder how this slipped by all this time. Feel free to submit a PR to fix this :)
