### ISSUE TITLE
Breadcrumb shows 'default' channel?

### ISSUE THREAD

**Issue by RCheesley** [rainlab/forum-plugin#132]
Hello,

When setting up a forum, we would like to use breadcrumbs as with the rest of the site.

With the individual forum post page, I've set the parent to be the channel page, however the URL used in the breadcrumb for the parent page is:

/forum/channel/default

when it should be, for example, 

/forum/channel/general-discussion

The channel page has a URL slug:

/forum/channel/:channelslug

so I think it is struggling to pull in the channel slug and instead defaulting to /default.

Any ideas how to work around this or if I missed setting something up correctly? 

The channel page works fine, as do all the other links, it's just the breadcrumb which seems a bit wonky and from a user perspective we think it's fairly important to have the breadcrumb available.

For reference, this is the plugin being used for the breadcrumbs: https://octobercms.com/plugin/mey-breadcrumbs

**Comment by LukeTowers** [comment]
@RCheesley that sounds like a problem for that plugin's author to deal with, not this plugin.
