### ISSUE TITLE
Integrate with RainLab.Notify

### ISSUE THREAD

**Issue by LukeTowers** [rainlab/forum-plugin#139]
It would be nice to be able to connect the forum plugin up to a slack channel for all new postings

**Comment by mjauvin** [comment]
@LukeTowers @bennothommo @daftspunk Is this still relevent since we now have notifications via RSS to Discord ?

**Comment by LukeTowers** [comment]
@mjauvin I think it would still be useful to integrate this with RainLab.Notify
