### ISSUE TITLE
Unable to fork Embed Topic Component

### ISSUE THREAD

**Issue by 4nik3t** [rainlab/forum-plugin#141]
I have inserted a embed Topic component inside my page . When I try to fork the component It gives me a error saying 
![image](https://user-images.githubusercontent.com/48653948/65371364-88c44700-dc80-11e9-9768-eb92e63aa0de.png)

I went through the logic of the component and saw that this component does not have a partials directory but uses the topic component partials
```php
$component = $this->addComponent('RainLab\Forum\Components\Topic', $this->alias, $properties);
```
I think of  a way of giving a friendly user message or else how can this be solved?

**Comment by bennothommo** [comment]
@aniket-magadum Would you mind providing a full backtrace of the error you encountered? Also, did this occur on a new page, or a page that had been created previously?

**Comment by aniket-magadum** [comment]
Here is the list of activities to perform to get this error.

1. Create a new CMS Page or open a existing page which you want to embed  the topic .
2. Add the Embed Topic component to the page like this 
![image](https://user-images.githubusercontent.com/48653948/65783944-968d3700-e16e-11e9-8a9b-30f5f23dc384.png)
3.  Now by clicking on the fork button the component is unable to create a copy of this.
![image](https://user-images.githubusercontent.com/48653948/65784012-c2a8b800-e16e-11e9-9fee-6a71c03520fa.png)

The possible reason this might be happening is that this component does not have a partial of itself but uses the partial of Topic Component.

**Comment by LukeTowers** [comment]
Fixed in https://github.com/octobercms/october/commit/c84c51c82009a84b546e5b8acdd9314906ceb162. Components without a `default` partial can't be forked.

**Comment by 4nik3t** [comment]
Nice @LukeTowers
