### ISSUE TITLE
Wrong link on the member name

### ISSUE THREAD

**Issue by faselunare** [rainlab/forum-plugin#142]
in the view 'latest topics' when i click on he member name, i get an url like '.../forum/member'
there is no slug... if im logged in, i see my personal page even if I click on another user's name

**Comment by LukeTowers** [comment]
Link?

**Comment by faselunare** [comment]
Is in my locale env
but you can check the topics template
where you can find this line 
```
 <a href="{{ topic.last_post_member.url }}">{{ topic.last_post_member.username }}</a>
```
from this {{ topic.last_post_member.url }} I expect something like that "forum/member/john-doe" instead of "forum/member"

**Comment by faselunare** [comment]
topic.last_post_member.slug contain the slug but if i use them with page to generate the correct link
```
{{ 'forum/member'|page({ slug: topic.last_post_member.slug }) }}
``` 
i get only this url /forum/member/ without the slug
if i add the slug by hand i get 404 page

**Comment by LukeTowers** [comment]
@faselunare what's the config for the page you have the topics component on? It needs to have the topicPage item set correctly otherwise it doesn't know what page to link to.
