### ISSUE TITLE
Quote not working

### ISSUE THREAD

**Issue by w3labz** [rainlab/forum-plugin#144]
HI,
Thanks for nice forum plugin.

I an testing the plugin and found that Quote button in Topics is not working. When I analysed the code, found that the Button code in the post.htm partial file under the Topic component was having following code:

```
  {% if topic.canPost %}
                <a href="javascript:;"
                    class="quote btn btn-sm btn-primary"
                    data-request-data="post: {{ post.id }}"
                    data-quote-button>
                    Quote
                </a>
            {% endif %}
```

This missing the **data-request="onQuote"**, so I added but still it does nothing.

Can you help me in locating the cause and how to correct it.

**Comment by bennothommo** [comment]
@w3labz I believe the quote function is done through JavaScript - can you confirm that all necessary JS files have been loaded?

**Comment by w3labz** [comment]
I think these are loaded as EDIT which is also there and load the edit form using AJAX is working properly.

These are the JS loaded on page:
```
<script src="{{ [
        'assets/js/jquery.js',
        'assets/js/bootstrap.min.js',
        'assets/js/jquery.parallax.js',
        'assets/js/owl.carousel.min.js',
        'assets/js/smoothscroll.js',
        'assets/js/wow.min.js',
        'assets/js/custom.js',
        '@framework',
        '@framework.extras']|theme }}"></script>
```

Did I missed any JS?

**Comment by LukeTowers** [comment]
@w3labz what about the `{% scripts %}` twig tag?

**Comment by SkyHolder** [comment]
`{% scripts %}` really solve this issue, thank you
