### ISSUE TITLE
A code block is trimed if placed as the first content of a Post

### ISSUE THREAD

**Issue by RomainMazB** [rainlab/forum-plugin#145]
Hi,
using a code block as the first content of a Post is a problem, you can just [preview a message on the official website](https://octobercms.com/forum/post?channel=3) to see it: copy/past the code below and click on preview.

Using this syntax as a a Post content:
```markdown
    <?php echo 'foo'; // Just a code block using "four spaces syntax"
```
will be parsed to:
```html
<p><?php echo 'foo';</p>
```

But it would have been parsed to:
```html
<pre><code><?php echo 'foo';</code></pre>
```

[This is actually a collateral "damage" of the `October\Rain\Database\Model` class](https://github.com/octobercms/library/blob/develop/src/Database/Model.php#L1210-L1212), so I'm not sure how it should be fixed properly?

The only idea I had works but it's not the most elegant: override the `setAttribute` method in `Post` and add a markdown comment at the beginning of the content so it won't be trimmed :face_with_head_bandage: .

    public function setAttribute($key, $value)
    {
        if ($key === 'content') {
            $value = '[//]: # (Do not trim me please!)' . "\r\n" . $value;
        }

        parent::setAttribute($key, $value);
    }

**Comment by bennothommo** [comment]
@RomainMazB I'll mark this as a bug, but I don't think it's going to be fixed any time soon as any fix I can think of would be a hack at best.

If someone needs to use a code block in the first line of the content, they should use a "fenced" code block instead, like as follows:

    ```
    <?php
    echo 'Hi';
    ?>
    ```

```php
<?php
echo 'Hi';
?>
```
