### ISSUE TITLE
How use rainlab username istead of {{ post.user.name }}

### ISSUE THREAD

**Issue by Hessel91** [rainlab/forum-plugin#151]
Hi there, 

since it is not possible to edit the {{ post.user.name }} in the front-end > i'd like to use rainlabs user.username. 
How can i replace {{ post.user.name }} for rainlabs user.username ?

**Comment by LukeTowers** [comment]
Just change it to `{{ post.user.username }}`?

**Comment by Hessel91** [comment]
fixex it. thanks for support. >  {{ post.member.user.username }}
