### ISSUE TITLE
How to change the generated forum username logic

### ISSUE THREAD

**Issue by schillerenrico** [rainlab/forum-plugin#152]
If you register with an mail, for example user@forum.com, the username for the forum will become user2. It takes the first part of the mail and adds a 2.

How can we set the username for forum by an register field like "username". username and username forum are separated and I dont know why? I would rather like to set them both to the same value.

Is there a feature / option planned or existing?

Thanks! You did a great job with your forum plugin!

**Comment by mjauvin** [comment]
The "2" comes from the existing user->id being appended to the email username, you can see this here:
```
    public static function getFromUser($user = null)
    {   
        if ($user === null) {
            $user = Auth::getUser();
        }

        if (!$user) {
            return null;
        }

        if ($member = $user->forum_member) {
            $member->setRelation('user', $user);
        }
        else {
            $generatedUsername = explode('@', $user->email);
            $generatedUsername = array_shift($generatedUsername);
            $generatedUsername = Str::limit($generatedUsername, 24, '') . $user->id;

            $member = new static;
            $member->user = $user;
            $member->username = $generatedUsername;
            $member->save();

            $user->forum_member = $member;
        }

        return $member;
    }
```

Unfortunately, this is not currently configurable.

Feel free to submit a PR that would allow this to be extended.
