### ISSUE TITLE
Any idea on how to allow Image/video uploading inside the post?

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/forum-plugin#153]
Any idea on how to allow Image/video uploading inside the post?

**Comment by daftspunk** [comment]
Hey @chrisvidal, unfortunately, this feature is not implemented and indeed it would be a cool feature to have. It could be based on GitHub's implementation and use an attachment relation to the post model with deferred binding, allowing the upload to be accepted before the post is made.

We would happily review a pull request that implemented this, or could implement it as part of a [premium support ticket](https://octobercms.com/premium-support).

**Comment by chrisvidal** [comment]
there are 2 approaches I guess: inline attachment (a la github) or (separate) file upload.
I was wondering about switching the standard form extarea control with a rich text editor that would directly allow this attachment upload. Will have a look

**Comment by daftspunk** [comment]
Taylor has described the requirement very well in this tweet: https://twitter.com/taylorotwell/status/1414029896351879168?s=21

**Comment by chrisvidal** [comment]
I implemented a simple project collaboration tool based on the Forum with an 'October way' solution for handling the file uploading
- plugin https://github.com/Voilaah/oc-basecamp 
- theme based on Rainlab Vanilla: https://github.com/Voilaah/oc-basecamp-theme

A channel belongs to a user group or not
a User belongs to a user group or not.

The theme will display the allowed channels for the current logged in user.
User can upload many files inside the posts/
