### ISSUE TITLE
Issue with Class Names in EmbedTopic and EmbedChannel Components

### ISSUE THREAD

**Issue by spanjaan** [rainlab/forum-plugin#155]
Hello @daftspunk,

Greetings,

I have found some missing class names in the `EmbedTopic` and `EmbedChannel` components. Specifically, in the `EmbedTopic` component at line 98, the code is as follows:

```
$component = $this->addComponent('RainLab\Forum\Components\Topic', $this->alias, $properties);
```

To fix this error, you need to correct the class name in both the `EmbedTopic` and `EmbedChannel` components. Please change `Topic` to `ForumTopic`:

```
$component = $this->addComponent('RainLab\Forum\Components\ForumTopic', $this->alias, $properties);
```

**After making this correction, the plugin works fine. However, the same topic is embedded in all blog posts. I have not yet resolved the issue of how to display separate embedded topics in each blog post.**

I hope you can resolve this issue soon.

Thank you.

**Comment by daftspunk** [comment]
Hi @spanjaan 

A fix has been added here: a4a7ba0e9c6b2db2611edafed54c4be010298256

It looks like the embedding feature is undocumented since we only use it internally. If possible, could you share your implementation (CMS template code?) so we can test it?

**Comment by chrisvidal** [comment]
I still can see this issue in the latest facing the same issue as the `v2.0.1` tag is not yet released.
could you publish this tag version please @daftspunk

**Comment by daftspunk** [comment]
Ok, v2.0.1 has been released
