### ISSUE TITLE
Badly formatted code blocks in emails

### ISSUE THREAD

**Issue by Flynsarmy** [rainlab/forum-plugin#33]
A forum member submitted [this post](http://octobercms.com/plugin/flynsarmy-menu/override-default-menu?page=1#post-2458) and it appeared in my email inbox like so:
![](http://i.imgur.com/ri4LEFQ.png)

This could be formatted much nicer.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
