### ISSUE TITLE
Badly formated messages in member page

### ISSUE THREAD

**Issue by xIamBlitz** [rainlab/forum-plugin#44]
While entering a member page, on latest post you can see a bad formatting, which gives weird marks � and also can't see markdown code used in topic page.

**Comment by daftspunk** [comment]
Can you take a screenshot? It could be caused by your theme perhaps?

**Comment by xIamBlitz** [comment]
Here they are:
Topic:(good)
![topic](https://cloud.githubusercontent.com/assets/10238145/6387762/cc2d730e-bd90-11e4-9763-62df1c523aa7.png)
Member:(bad)
![member](https://cloud.githubusercontent.com/assets/10238145/6387764/e20984b0-bd90-11e4-9b05-be3edae4189d.png)

**Comment by daftspunk** [comment]
This looks like it is caused by the webfont used by your theme, it is missing those characters maybe?
