### ISSUE TITLE
return bbcode support or something else

### ISSUE THREAD

**Issue by rebornishard** [rainlab/forum-plugin#47]
please bring this one back, or another alt for markdown
thanks

**Comment by Shahiem** [comment]
Check out my plugin https://github.com/Shahiem/bbcode-plugin

**Comment by rebornishard** [comment]
@Shahiem : i put this for forum post.php line 144 in this file : forum-plugin/models/Post.php , i love your plugin so much but that line break bbcode completely and left only video to working fine, check your octobercms support page, i post something there, and pull to your plugin

thanks

**Comment by Shahiem** [comment]
What kind of error message do you get?

**Comment by rebornishard** [comment]
@Shahiem : before it break bbcode markup, but i tried latest source from forum-plugin and all is well,
thanks
forum-plugin/models/Post.php
in line 144 that update make bbcode working again
