### ISSUE TITLE
Component Topic List give error for logged in user

### ISSUE THREAD

**Issue by rebornishard** [rainlab/forum-plugin#48]
Call to a member function gt() on a non-object

/public_html/plugins/rainlab/forum/models/TopicWatch.php line 60

**Comment by daftspunk** [comment]
Should have been fixed already in 4acb3e84b4a7742f6cb3a3c23af46ba56e163f4b

**Comment by rebornishard** [comment]
thanks daftspunk, but not that one,
let me show some ss
i add Topic List from component,
if i'm not login in front end
![not login user](https://docs.google.com/file/d/0B8zkKK9h3vQeVnRRY1ZVVFU5N1E/edit?usp=drivesdk)
if i login in front end
![login user](https://docs.google.com/file/d/0B8zkKK9h3vQeazhpTkZOUm1Hdnc/edit?usp=drivesdk)

thanks
