### ISSUE TITLE
Forum index looks ugly (?)

### ISSUE THREAD

**Issue by Knight-Industries** [rainlab/forum-plugin#49]
Hi,

http://knight-industries.org/site/forum/

Is this because of my Design or why?

Thanks

**Comment by daftspunk** [comment]
Hello,

This forum looks pretty good

http://octobercms.com/forum

It must be because of your design.

Also, the site you linked has a password on it =)

**Comment by Knight-Industries** [comment]
Oh sorry I removed the HTACCES Password Dialog. Try now.
