### ISSUE TITLE
[Bug] Restrict HTML tag usage

### ISSUE THREAD

**Issue by alxy** [rainlab/forum-plugin#54]
It seems, the forum is vulnerable to xss attacks, specifically in code-blocks. They dont seem to be excaped properly:

http://octobercms.com/forum/post/how-to-display-pictures-in-backend-lists#post-5259

**Comment by daftspunk** [comment]
This isn't XSS vunerable per say, it just means we allow most HTML tags inside post content. We should look at restricting the tags perhaps?

**Comment by CptMeatball** [comment]
+1. Current state of the forum is not behaving like it should. As you can see, users that do no 'escape' forms in the post, break the thread.

<img width="920" alt="screen shot 2015-09-17 at 08 32 46" src="https://cloud.githubusercontent.com/assets/1681727/9926613/5c267c64-5d17-11e5-9d9e-0b22d01b9274.png">

[Link to thread](https://octobercms.com/forum/post/form-sends-duplicate-email) and [another example](https://octobercms.com/forum/post/problem-with-inserting-into-database-function-runs-3-times)

**Comment by daftspunk** [comment]
Renders as markup

```
Hi, I'm trying to insert some data submitted on a form into my database, the problem is, that the function runs 3 times for some reason, so it inserts 3 the same record into the db.
i also tried with just an empty form and a submit button wich triggers an alert, the alert comes 3 times

heres my code:


<form data-request="onInsert">
             <input type="text" name="naam"></input>
             <input type="text" name="achternaam"></input>
             <input type="text" name="leeftijd"></input>
            <input type="submit" value="add to aan DB"></input>
</form>

function onInsert()
  {
      $naam = post('naam');
      $achternaam = post('achternaam');
      $leeftijd = post('leeftijd');
      
      Db::insert('insert into test_tabel (naam, achternaam, leeftijd) values (?, ?, ?)', [$naam, $achternaam, $leeftijd]);
   }
```

**Comment by daftspunk** [comment]
This was fixed a while back.
