### ISSUE TITLE
Grouping error for Postgres after plugin installation

### ISSUE THREAD

**Issue by b0gok** [rainlab/forum-plugin#64]
>"SQLSTATE[42803]: Grouping error: 7 ERROR: column "rainlab_forum_channels.nest_left" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: ...ainlab_forum_channels" where "slug" = $1 order by "nest_left... ^ (SQL: select count(*) as aggregate from "rainlab_forum_channels" where "slug" = channel-orange order by "nest_left" asc)" on line 624 of C:\Bitnami\wampstack-5.4.37-0\apache2\htdocs\october_clear\vendor\laravel\framework\src\Illuminate\Database\Connection.php

**Comment by dcrawkstar** [comment]
Please review this: https://github.com/octobercms/october/issues/1111
