### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by gaaarfild** [rainlab/forum-plugin#65]
After installation process, it doesn't appear anywhere. 
The only thing that I mentioned is menu entry in backend only on "plugins manage" page, and it shows `rainlab.forum::lang.settings...blabla`.

**Comment by daftspunk** [comment]
It looks like you may have the RainLab.User plugin missing, the Forum depends on it, so try installing that first

**Comment by gaaarfild** [comment]
Now all works. Thank you very much.
I thought, that dependencies are pulling automatically. :)
