### ISSUE TITLE
Embedded comments in a single post is repeated in all posts

### ISSUE THREAD

**Issue by laics1984** [rainlab/forum-plugin#66]
Hi all, 

I have a embedded comment is repeated in every posts in my blog. May I know what is the problem?

**Comment by Larraby** [comment]
It seems to me I have the same problem.
I've repeated all the instrucions from this video:
https://octobercms.com/blog/post/building-a-blog-and-forum
And only first blog post topic is created, and next don't

**Comment by jimibi** [comment]
I have the same problem

**Comment by ScholarshipDevelopers** [comment]
https://github.com/rainlab/forum-plugin/issues/99 

For "Embed code" use the "external parameter"        >_   button.

**Comment by JoakimBo** [comment]
I dont think this is a bug (yet). Tested this myself and @ScholarshipDevelopers seems to be correct, the external parameter needs to be used. What makes this somewhat difficult to play around with is that there are no menu to manage all of the channels, topics and topic posts from the backend.
Perhaps both the management of the forum through the backend and an update to how to set up the forums are needed.

**Comment by LukeTowers** [comment]
I'm open to suggestions, perhaps a PR with a images of the UX that you're describing @JoakimBo

**Comment by JoakimBo** [comment]
@LukeTowers Unsure if this is something I can prioritize anytime soon. On the top of my head I was thinking something close to how blog posts are managed.   
If I remember correctly the only config availible right now is the management of channels it would probably be a good idea for backend users to be able to check all topics on a channel and their respective posts. If I find myself with time to kill someday I'll see if I can do a mockup or prototype.

**Comment by LukeTowers** [comment]
Sounds good, looking forwards to that @JoakimBo 😄
