### ISSUE TITLE
Update version.yaml?

### ISSUE THREAD

**Issue by damarisz** [rainlab/forum-plugin#68]
The file `plugins/rainlab/forum/models/Post.php` was modified in b89e41df934a3a943adfdf53f367b02d51be7af7 but I never received a plugin update notice in the backend. I had to manually change my file. This error was preventing users from creating and commenting on posts. Does version.yaml need to be updated to reflect this change?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
