### ISSUE TITLE
Button post not working

### ISSUE THREAD

**Issue by PanRada** [rainlab/forum-plugin#70]
Can u help me with issue 

In Channel page is button to redirect to creat new topic - but on me not working correct all the time redirect me to chanel page 
as soon I undestand this code 
<a href="{{ topicPage|page }}?channel={{ channel.id }}" class="btn btn-primary btn-block">
it look is some wrong or I'm wrong

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
