### ISSUE TITLE
Backend Edit Channels Error - slug not getting replaced.

### ISSUE THREAD

**Issue by jayalfredprufrock** [rainlab/forum-plugin#74]
When clicking on a channel to edit it within the backend I get the following error:

Form record with an ID of :id could not be found.

I've tried deleting and creating new channels as well as uninstalling and reinstalling the forum component. Nothing seems to make this error go away. If I manually replace ":id" with the actual id of a channel everything works as expected.

**Comment by lucaspark** [comment]
I have also started to get the same issue. Something seems to have changed with the latest forum plugin update. I was working before...

**Comment by gregorybleiker** [comment]
I had the same problem. You need to change 
```
    /**
     * @var array The attributes that should be visible in arrays.
     */
    protected $visible = ['title', 'description'];
```
to
```
    /**
     * @var array The attributes that should be visible in arrays.
     */
    protected $visible = ['id', 'title', 'description'];
```
in model/Channel.php
I'll do a pull request or maybe @daftspunk will pick it up, which would be even nicer ;)
Maybe id was visible by default sometime earlier on?

**Comment by daftspunk** [comment]
This will be fixed in the next build (Build 288+)
