### ISSUE TITLE
Unable to update channels

### ISSUE THREAD

**Issue by fabriciorabelo** [rainlab/forum-plugin#75]
I think the bug is with the current OctoberCMS build, because I was cloning the forum channel to use in my own plugin and I had the same error. When you create a channel item and will update by clicking it on channels list, I got the error below:

![captura de tela 2015-08-06 as 15 14 25](https://cloud.githubusercontent.com/assets/11408273/9119776/ef36e3f2-3c4e-11e5-8053-da4bff87e8ad.png)

![captura de tela 2015-08-06 as 15 14 44](https://cloud.githubusercontent.com/assets/11408273/9119775/ef360f36-3c4e-11e5-9bda-f3fce3b28323.png)

![captura de tela 2015-08-06 as 15 26 10](https://cloud.githubusercontent.com/assets/11408273/9119893/92287562-3c4f-11e5-9ec0-1e4e200c1844.png)

![captura de tela 2015-08-06 as 15 26 26](https://cloud.githubusercontent.com/assets/11408273/9119892/9224dc4a-3c4f-11e5-8733-0104206b9ea5.png)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
