### ISSUE TITLE
WYSIWYG Support

### ISSUE THREAD

**Issue by vanmil** [rainlab/forum-plugin#79]
Hi RainLab, 

Would some kind of wysiwyg support be possible for the forum plugin? I've made a website for a community, (a small) part of the website is a private forum for all the members. Now all those non-technical users have to work with Markdown syntax (easy if you know the syntax, but difficult if you are a 'non-technical' user like my mom). I think for those users and all non-technical users in general this plugin will be far better if it had some kind of wysiwyg posting capabilities. 

My question: If there isn't already support for wysiwyg posting, would it be possible to add this in the feature?

Many thanks for all your great work,

Jelle

**Comment by Shahiem** [comment]
http://octobercms.com/plugin/shahiemseymor-bbcode

**Comment by JellevanMil** [comment]
Hi Shahiem, thanks for your reaction. Can you maybe give this question a look? :) http://octobercms.com/plugin/shahiemseymor-bbcode/implement-bbcode-with-rainlabforum

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
