### ISSUE TITLE
i want to translate the quote text

### ISSUE THREAD

**Issue by abargel** [rainlab/forum-plugin#82]
i want to translate the quote text.
example:

> **user** said:

how can i do this without edit the js file?

**Comment by Shiro-dono** [comment]
that's very easy, all u have to do is create another template so it won't change when the plugin updates.
Go to: plugins/rainlab/forum/components/...   and see where THAT thing is for what u want to change.

In the Forum page or Forum chanels what u have to do to change the tamplate is this: {% component 'forumChannelsForum::template_name.htm' %}
Good Luck

**Comment by daftspunk** [comment]
Take a look at the documentation on how to customize the default markup that comes with components:

http://octobercms.com/docs/cms/components#customizing-default-markup

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
