### ISSUE TITLE
override getFromUser method

### ISSUE THREAD

**Issue by sNuuFix** [rainlab/forum-plugin#84]
Hello,
I'm researching ways to override getFromUser method in Member model without modifying the code there and break the site when updating forum plugin and I can't seem to find a way to do it. Should I replace forum_member preperty reference for User model from my own plugin or extend Member model and replace all namespaces for RainLab's one? They both seem bad ways.

**Comment by daftspunk** [comment]
It's difficult to discuss a solution without first understanding the problem. Please, explain the problem itself and not the solution that you have in mind. Thanks! For more info, see http://mywiki.wooledge.org/XyProblem

**Comment by sNuuFix** [comment]
You are 100% correct, my mistake of not providing background data.

My project involves specific implementation of user registration workflow. I don't have much information about user, no email, so name/surname, only username and hashed password from external source. Registration process is outside of octobercms, so it can only be modified with database insert trigger. If the user visits forum without registering from site (in our case 100% of cases), the getFromUser method gets called to get his default username. I want it to be exactly the same as username, because it will not be modified from profile and it represents his real identity in my case. This function only generates ID number, because there is no email present.

Only recently I ralized I can just override all forum partials and just display real username from user table, but then there is unnescessary data in database created and I am perfectionist.

So, the question now would be, should I jsut change displayed output template od there is other possibility?

P.S. Sorry about very delayed response, this project is secondary for me, but it's personal, so I want to do my best.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
