### ISSUE TITLE
Fatal Error Exception

### ISSUE THREAD

**Issue by gayathrics** [rainlab/forum-plugin#89]
Just installed the plugin and I get this error - 
syntax error, unexpected 'if' (T_IF), expecting function (T_FUNCTION)
/var/www/kevinw.me/public_html/oct/plugins/rainlab/forum/components/Topic.php line 175

Noticed an extra } in code -
in line 172 that needs to be removed

**Comment by daftspunk** [comment]
Thanks @gayathrics 

@gergo85 this is why it is hard to accept clean up PRs
