### ISSUE TITLE
syntax error, unexpected 'if' (T_IF), expecting function (T_FUNCTION)

### ISSUE THREAD

**Issue by tfleong-spiralvibe** [rainlab/forum-plugin#90]
syntax error, unexpected 'if' (T_IF), expecting function (T_FUNCTION)
C:\xampp\htdocs\october\demo\plugins\rainlab\forum\components\Topic.php line 175

175    if ($channel) { <--- this line
176        $channel->setUrl($this->channelPage, $this->controller);
177    }

I got this error on the CMS section after installing the plugin. Is it an installation issue?

**Comment by daftspunk** [comment]
Duplicate #89

**Comment by daftspunk** [comment]
Install the plugin a second time (over the top) to fix it

**Comment by tfleong-spiralvibe** [comment]
Works, thanks! :D
