### ISSUE TITLE
Forum - Blog connection not working

### ISSUE THREAD

**Issue by IrealiTY** [rainlab/forum-plugin#91]
Hello,

I've been looking at the Vanilla Theme how it sets up the Blog comments to be Forum posts but it doesn't seem to work.

Here a screenshot from the backend:
![untitled-1](https://cloud.githubusercontent.com/assets/1223686/17871447/e1db90a0-68bb-11e6-9a90-cc0b1ecc79b9.jpg)

Is there a certain setup that needs to be done?

**Comment by b0gok** [comment]
Do you have a comment block on post's page?

**Comment by IrealiTY** [comment]
You mean in the CMS backend or on the front end?
On the Front End I do see a comments field and if I comment in there it's just a comment on the blog post - not on the forums :)

**Comment by b0gok** [comment]
> You mean in the CMS backend or on the front end?
The second one, on the front end.

**Comment by b0gok** [comment]
@IrealiTY try to choose this option
![image](https://cloud.githubusercontent.com/assets/4283162/17987357/3574319a-6b28-11e6-8000-77f810454c97.png)

**Comment by IrealiTY** [comment]
Oh OK I see. I should have really looked deeper on the forums. Thanks for pointing that out to me.

It seems that the blog-post itself is not a post and you only see the comments - is there a possibility for that? (Blogpost itself being the 1st post in its own thread or an excerpt?)

**Comment by Shiro-dono** [comment]
Yes, just look at the vid:https://octobercms.com/plugin/rainlab-blog and change on how many post should there be viewed on the page, u can also change the template of the post to show only what u want

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
