### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by Shiro-dono** [rainlab/forum-plugin#94]
Hello,
Besides Forum plugin, I am using the standard plugins, but I am using a Foundation Theme. Is there a compatibility issue between Bootstrap and Foundation when causing errors for the plugins themselves?

**Comment by daftspunk** [comment]
There is no dependency on any front end system, the default markup provided by the forum plugin acts as an example (based on the "demo" reference theme that uses Bootstrap). See the documentation on how to customize it for Foundation:

http://octobercms.com/docs/cms/components#customizing-default-markup

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
