### ISSUE TITLE
Log In Forum Error - function gt()

### ISSUE THREAD

**Issue by Shiro-dono** [rainlab/forum-plugin#95]
Hello,
The following error occurs only when the user loges in and it happens on the forum pages.
![capture](https://cloud.githubusercontent.com/assets/13037716/18195491/69a8df8e-70f4-11e6-8c7d-62dd65784ef7.PNG)
This error does not appear when the user is logged out.

The comments on the pages work.
Now the solution is to actually write at least ONE comment on at leas ONE post/blog. So if you do this, the error will not appear.

Re: Also when i enter the "Comments section that i created" it's the same problem, so i have to create at least on comment in each and every post so I don't have that error.
P.S. using foundation theme

Is there a solution to the error above without resorting to writing comments in the post/blogs?

**Comment by daftspunk** [comment]
Wasn't able to replicate this, but will add some exception handling to target this specific error.

**Comment by daftspunk** [comment]
Update to v1.1.1 to get the fix

**Comment by Shiro-dono** [comment]
Thx, it works, will update, if there are any more issues
