### ISSUE TITLE
Managing Comments

### ISSUE THREAD

**Issue by Shiro-dono** [rainlab/forum-plugin#96]
Hello,
Is there a way for the admin to delete the unwanted comments in the blog section?

**Comment by daftspunk** [comment]
Forum administrators can delete comments. Navigate to the User in the backend, click the Forum tab, and place a tick in the forum administrator checkbox. Now this user can delete comments on the front end.

**Comment by Shiro-dono** [comment]
Yes, thx, it was somewhat there, User->"Person"->Update details-> Forum Tab->Forum admin. SAVE.
I have the POWER to delete :)

**Comment by mpenna** [comment]
Sorry for reopening this. Just to make sure, can the backend users not be assigned as forum moderators? I'm logged in with super-user admin and I don't see where or how I can manage comments.

Regarding the solution provided above, I reckon the (frontend) user, once elevated as forum moderator, will only be able to delete comments via the frontend, right? 

And last but not least...  once elevated as a forum moderator, the user will have that privilege regardless of either channel or topic, right? Or can the moderation have a more "cherry-picked" approach?
