### ISSUE TITLE
Embed Title show just 'Post'

### ISSUE THREAD

**Issue by Shiro-dono** [rainlab/forum-plugin#97]
Hello,
I followed the video on the blog->forum tutorial, but i have an issue with the Forum Chanel.
So, i do have the: /articles/:slug and /articles/post/:slug for the blog and posts with the right URL's
In the Post page I have the Embed Topic with the Embed Code (>_:slug)
![embedtipic](https://cloud.githubusercontent.com/assets/13037716/18246425/488a125a-7374-11e6-8beb-a2418ac10a12.PNG)
This is what appears in the Form Chanel
![formchanel](https://cloud.githubusercontent.com/assets/13037716/18246515/c1576af2-7374-11e6-9085-5fe94ffbc185.PNG)
This is the inspect element
![inspectpost](https://cloud.githubusercontent.com/assets/13037716/18246559/05064796-7375-11e6-88ae-14f68f37644f.PNG)

What am i doing wrong, cuz in the vid i did it like him, except that there are a couple of things missing since the plugin update that i didn't have to enter.
Thx in advanced

**Comment by Shiro-dono** [comment]
Hello, I found the problem, apparently in the video when the guy makes the post section he enters this:
function onEnd() {$this->page->title = $this['post']->title;} - To view the title of the post
And this is apparently very important for the Embed Topic so that it knows what title to take;

Now, my mistake was that I modified the template and I already had the title:
So the modified template has no effect over the Embed Topic so it doesn't know how to take the title from the custom template (which is in the cpanel plugin/rainlab)
something like {% component 'blogPost::default-post-4.htm' %}

Sorry for not following the video like a normal person 
P.S. Please specify when things are important for other things to work

**Comment by daftspunk** [comment]
Thanks for the feedback. I wonder if this appears in the complimentary theme, RainLab.Vanilla. It probably is a better way to approach it.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
