### ISSUE TITLE
Forum Chanel No/Empty Author

### ISSUE THREAD

**Issue by Shiro-dono** [rainlab/forum-plugin#98]
Hello
So i have this in the Forum Chanel Page: 
![post-1nothing](https://cloud.githubusercontent.com/assets/13037716/18250904/b32c6986-738e-11e6-9a6d-9c94a348e4ba.PNG)
It does not show the author AND it also show (-1) Replies (i don't really mind this one)
One question would be: how to delete the Topic Itself?
Thx

**Comment by Shiro-dono** [comment]
Hello,
Yah, my bad, delete the comments, topic remains, but that's good
And of course if nobody posts in them => no author (duh)
In other news, still don't know why it shows  "-1" at Replies

**Comment by daftspunk** [comment]
When deleting the last comment, the topic should also be deleted. Is it not the case? If so, as per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
